### ISSUE TITLE
Custom key option in reducer

### ISSUE THREAD

**Issue by nutboltu** [yusinto/ld-redux#16]
In the existing approach, in reducer, we receive a camelCased key based on our feature flag key. If we have a long key name `this-is-a-long-long-long-key-name`, it gives a key `thisIsALongLongLongKeyName` which violates [eslint id-length](https://eslint.org/docs/rules/id-length).
It would be a good feature, if we provide custom key instead of camelCased key.
Proposal approach:
```
const flags = [
  {
    key: 'feature-flag-key',
    default: false,
    reduxKey: 'myCustomKey',
  },
];
```
In the reducer, we should receive a LD object with our custom key.

```
{
  LD: {
   isLDReady: true,
   myCustomKey: false
  }
}
```

**Comment by yusinto** [comment]
Thanks for the request @nutboltu ! It could be helpful to alias key names like this, although it creates an extra layer of abstraction which makes flag retrieval more complex. You'll have to inspect the `flags.json` file every time when retrieving them or remember them which I think is a problem.

In your case, if `eslint` complains about the long name, I think that's a sign that you should avoid using such long names. A feature flag name should be short and concise, just like a good variable name. If you need additional info, you can always add them to the description field in Launch Darkly. I think that's the best solution for you.

**Comment by nutboltu** [comment]
@yusinto Thanks for  the feedback. In our case we have to put few information in our key which makes it longer. So I can't change the key but I may wrap this package with my custom key in my codebase. No worries.
