### ISSUE TITLE
init with dispatch instead of store

### ISSUE THREAD

**Issue by mlund01** [yusinto/ld-redux#18]
I have a suggestion that would be an easy change, but also a breaking change that I believe would make the init method more flexible on where it can be used. I can make the PR, but wanted to start a discussion on it first.

Problem: `ldRedux.init` expects the redux store as the second arg. This works great if you are initiating  `ldRedux` close to where you are initiating the redux store. However, in practice, the `ldRedux` is more likely initiated in close proximity to where the user is created/authenticated, when the data is available. In our case, that handler is a thunk, which does not have access to `store` directly.

Solution: Based on the code in https://github.com/yusinto/ld-redux/blob/master/src/init.js, the only usage of `store` is to call `store.dispatch`. `store` by itself is not something that is commonly (or easily) passed around. However, `dispatch` is meant to be passed around in both connected components and middleware such as `redux-thunk`. So  as an easy way to make `init` more flexible in where it can be used, the proposed solution is to replace `store` with `dispatch` as the second argument of `ldRedux.init` and call it directly within the underlying init methods

**Comment by yusinto** [comment]
Hi @mlund01 apologies for the slow reply. I have a situation like yours in my app and the way I solve it is to init at the start of the app, then on login I change the ld user context by calling `ldClient.identify` like documented [here](https://docs.launchdarkly.com/docs/js-sdk-reference#section-changing-the-user-context).

Your suggestion changing store to dispatch is actually not a bad idea although it's a breaking one. If you can please submit a PR, I will definitely review and merge.

Thanks!
