### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by vireshshah** [yusinto/ld-redux#22]
Thanks @yusinto  for such a great library. I'm getting below minor warning in console. Looks like it's coming from main library ldclient-js. May be we can try bumping up version. Not sure whether they've fixed it.

> [LaunchDarkly] "default export" is deprecated, please use "named LDClient export"

**Comment by yusinto** [comment]
Hi @vireshshah thanks for reporting this issue! I'll fix this soon.

**Comment by vireshshah** [comment]
Sure. Thanks @yusinto

**Comment by yusinto** [comment]
@vireshshah I finally fixed this! Upgrade to [v3.2.1](https://github.com/yusinto/ld-redux/releases/tag/v3.2.1) and this should be fixed.

**Comment by vireshshah** [comment]
Superb @yusinto. Thanks a lot!
