### ISSUE TITLE
Upgrade to new LD client package names

### ISSUE THREAD

**Issue by tedpennings** [yusinto/ld-redux#32]
Hi! 

I love this library. I've been using it for like three years and it's the best.

Can you upgrade to the new LD client libraries, `launchdarkly-js-client-sdk` and the like? 

Package managers won't upgrade past 2.10.2 because the package name has changed. Details are here: https://github.com/launchdarkly/js-client-sdk/blob/master/CHANGELOG.md#2103---2019-05-08

I would be open to doing some of the work if you have an idea of how best to do this. Would it be a new major? I don't think the ld-redux API would need to change much, so perhaps it can be a minor? 

Thank you!

**Comment by thiskevinwang** [comment]
+1! ❤️

**Comment by yusinto** [comment]
Hi @tedpennings thanks for submitting this. I think this can be a minor upgrade. If you can submit a PR that will be awesom!

**Comment by thiskevinwang** [comment]
@yusinto, does this look like a straight forward upgrade from

`ldclient-js @ 2.6.0` to `launchdarkly-js-client-sdk @ 2.13.0`

?

**Comment by yusinto** [comment]
It does look like it's just a straightforward upgrade. The tests should tell us if anything serious is broken.

**Comment by thiskevinwang** [comment]
Hey @yusinto, could you take a look at this #36 ?

The fact that LD `2.6.0` doesn't internally deal with a null-userId, is a huge bummer. :(

**Comment by yusinto** [comment]
This has been fixed in [v3.3.1](https://github.com/yusinto/ld-redux/releases/tag/v3.3.1)
