### ISSUE TITLE
`subscribeToChanges` always uses camelCase

### ISSUE THREAD

**Issue by enceeobee** [yusinto/ld-redux#63]
Hello 👋 ,

First, thank you for this package! It's wonderful 😄 

### Issue

I recently noticed that `subscribeToChanges` always uses a camelCase flag key when updating the store, even when `useCamelCaseFlagKeys` is set to `false`.

I don't think the fix should be too difficult, and I can probably supply a PR for it soon, but I wanted to open an issue for posterity.

### Steps to reproduce

1. init ld-redux setting `useCamelCaseFlagKeys` to `false`

	  ```javascript
	  ldRedux.init({
	    clientSideId: 'your-client-side-id',
	    dispatch: store.dispatch,
	    useCamelCaseFlagKeys: false
	  });
	  ```

2. Later, identify a new user, which will dispatch an event(s) to update the store once the new flag values are ready

	  ```javascript
	  window.ldClient.identify({key: 'someUserId'});
	  ```

3. Observe that the flag key in the SET_FLAG action is incorrectly sent in camelCase (e.g. `'my-kebab-case-flag'` is updated as `'myKebabCaseFlag'`)

### Screenshots

Here's an example of a flag being updated in camelCase, when it should be kebab-case

<img width="852" alt="camelCase" src="https://user-images.githubusercontent.com/9545215/133624467-9dc6ab47-9ceb-45ee-b17a-0e959eeae2f6.png">

**Comment by yusinto** [comment]
The fix for this has been merged and released in [v3.3.4](https://github.com/yusinto/ld-redux/releases/tag/v3.3.4).
